<table border="1">
    <thead>
        <tr>
            <th>Method</th>
            <th>Route</th>
            <th>Name</th>
            <th>Handler</th>
            <th>Before Filters</th>
            <th>After Filters</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>GET</td>
            <td>altlogin</td>
            <td>»</td>
            <td>\App\Controllers\Login::altlogin</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>/</td>
            <td>»</td>
            <td>\App\Controllers\Home::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>contact</td>
            <td>»</td>
            <td>\App\Controllers\Contact::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>blog</td>
            <td>»</td>
            <td>\App\Controllers\Blog::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>blog/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Blog::content/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>informations</td>
            <td>»</td>
            <td>\App\Controllers\Informations::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>informations/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Informations::info/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>pages</td>
            <td>»</td>
            <td>\App\Controllers\Pages::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/product</td>
            <td>»</td>
            <td>\App\Controllers\Product::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin</td>
            <td>»</td>
            <td>\App\Controllers\Admin::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/manage/pages</td>
            <td>»</td>
            <td>\App\Controllers\Pages::manage</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/manage/static_pages</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::manage</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/login</td>
            <td>»</td>
            <td>\App\Controllers\Login::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/register</td>
            <td>»</td>
            <td>\App\Controllers\Login::register</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>logout</td>
            <td>»</td>
            <td>\App\Controllers\Login::logout</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/user/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\User::user/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/test/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Admin::test/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>page/(.*)/(.*)/(.*)(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Home::page/$1/$2/$3/$4</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>page/(.*)/(.*)/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Home::page/$1/$2/$3</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>page/(.*)/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Home::page/$1/$2</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>page/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Home::page/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>page</td>
            <td>»</td>
            <td>\App\Controllers\Home::page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/static_page</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::crud</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/manage/static_pages/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::manage_static_page/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>admin/static_page/listGambar</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::listGambar</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>client</td>
            <td>»</td>
            <td>\App\Controllers\Client::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>client/sendmail</td>
            <td>»</td>
            <td>\App\Controllers\Client::sendEmail</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>clientlogout</td>
            <td>»</td>
            <td>\App\Controllers\Client::clientlogout</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>client/verify/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Client::verify/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>GET</td>
            <td>client/verifikasi/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\Client::verifikasi/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/tambah_group</td>
            <td>»</td>
            <td>\App\Controllers\Product::tambah_group</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/select_group</td>
            <td>»</td>
            <td>\App\Controllers\Product::select_group</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/deleted_group</td>
            <td>»</td>
            <td>\App\Controllers\Product::deleted_group</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/purge_group</td>
            <td>»</td>
            <td>\App\Controllers\Product::purge_group</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/upload</td>
            <td>»</td>
            <td>\App\Controllers\Product::upload</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/update_cat</td>
            <td>»</td>
            <td>\App\Controllers\Product::update_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/hapus_cat</td>
            <td>»</td>
            <td>\App\Controllers\Product::hapus_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/restore_cat</td>
            <td>»</td>
            <td>\App\Controllers\Product::restore_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/product/create</td>
            <td>»</td>
            <td>\App\Controllers\Product::create</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/login</td>
            <td>»</td>
            <td>\App\Controllers\Login::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>product/listdataProduct</td>
            <td>»</td>
            <td>\App\Controllers\Product::listdataProduct</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/listdata_user</td>
            <td>»</td>
            <td>\App\Controllers\User::listdata_user</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/tambah_admin</td>
            <td>»</td>
            <td>\App\Controllers\User::tambah_admin</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/hapus_user</td>
            <td>»</td>
            <td>\App\Controllers\User::hapus_user</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/reset_password</td>
            <td>»</td>
            <td>\App\Controllers\User::reset_password</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/ubah_status_user</td>
            <td>»</td>
            <td>\App\Controllers\User::ubah_status_user</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/ubah_level_user</td>
            <td>»</td>
            <td>\App\Controllers\User::ubah_level_user</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/listdata_client</td>
            <td>»</td>
            <td>\App\Controllers\User::listdata_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/tambah_client</td>
            <td>»</td>
            <td>\App\Controllers\User::tambah_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/hapus_client</td>
            <td>»</td>
            <td>\App\Controllers\User::hapus_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/reset_password_client</td>
            <td>»</td>
            <td>\App\Controllers\User::reset_password_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/user/ubah_status_client</td>
            <td>»</td>
            <td>\App\Controllers\User::ubah_status_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>pages/listdata_pages</td>
            <td>»</td>
            <td>\App\Controllers\Pages::listdata_pages</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/tambah_page</td>
            <td>»</td>
            <td>\App\Controllers\Pages::tambah_page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/hapus_page</td>
            <td>»</td>
            <td>\App\Controllers\Pages::hapus_page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/detail</td>
            <td>»</td>
            <td>\App\Controllers\Pages::detail</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/deleted_page</td>
            <td>»</td>
            <td>\App\Controllers\Pages::deleted_page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/restore_page</td>
            <td>»</td>
            <td>\App\Controllers\Pages::restore_page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/update_page</td>
            <td>»</td>
            <td>\App\Controllers\Pages::update_page</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/cat_list</td>
            <td>»</td>
            <td>\App\Controllers\Pages::cat_list</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/subcat_list</td>
            <td>»</td>
            <td>\App\Controllers\Pages::subcat_list</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/tambah_cat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::tambah_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/update_cat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::update_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/update_subcat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::update_subcat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/hapus_cat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::hapus_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/hapus_subcat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::hapus_subcat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/page/tambah_subcat</td>
            <td>»</td>
            <td>\App\Controllers\Pages::tambah_subcat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/menu</td>
            <td>»</td>
            <td>\App\Controllers\Home::menu</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/menu_cat</td>
            <td>»</td>
            <td>\App\Controllers\Home::menu_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/menu_sub_cat</td>
            <td>»</td>
            <td>\App\Controllers\Home::menu_sub_cat</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/get_menu_array</td>
            <td>»</td>
            <td>\App\Controllers\Home::get_menu_array</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/static_page/(.*)</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::crud/$1</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/static/ubah_status</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::ubah_status</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/upload/tinymce</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::tinymceUpload</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/static/deleteGambar</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::deleteGambar</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/static/select_client</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::select_client</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>admin/static/select_produk</td>
            <td>»</td>
            <td>\App\Controllers\StaticPages::select_produk</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>client</td>
            <td>»</td>
            <td>\App\Controllers\Client::index</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getContactUs</td>
            <td>»</td>
            <td>\App\Controllers\Home::getContactUs</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getSlider</td>
            <td>»</td>
            <td>\App\Controllers\Home::getSlider</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getService</td>
            <td>»</td>
            <td>\App\Controllers\Home::getService</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getPortfolio</td>
            <td>»</td>
            <td>\App\Controllers\Home::getPortfolio</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getTestimonial</td>
            <td>»</td>
            <td>\App\Controllers\Home::getTestimonial</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getPartner</td>
            <td>»</td>
            <td>\App\Controllers\Home::getPartner</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getOffer</td>
            <td>»</td>
            <td>\App\Controllers\Home::getOffer</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>POST</td>
            <td>home/getGroupProduct</td>
            <td>»</td>
            <td>\App\Controllers\Home::getGroupProduct</td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
