<?php $editing = !empty($editingProduct); ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h2 class="mb-1">Produk Reseller</h2><p class="text-muted mb-0">Kelola model, bahan, warna, ukuran, dan harga dasar privat.</p></div><a href="<?= base_url('admin/resellers') ?>" class="btn btn-outline-dark"><i class="fas fa-users me-2"></i>Pengajuan Reseller</a></div>
<?php if ($success = session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc($success) ?></div><?php endif; ?>
<?php if ($error = session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc($error) ?></div><?php endif; ?>
<?php if ($errors = session()->getFlashdata('errors')): ?><div class="alert alert-danger"><ul class="mb-0"><?php foreach ((array) $errors as $error): ?><li><?= esc($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

<div class="admin-card mb-4"><div class="card-header"><i class="fas fa-<?= $editing ? 'pen' : 'plus' ?> me-2"></i><?= $editing ? 'Edit Produk' : 'Tambah Produk' ?></div><div class="card-body"><form action="<?= $editing ? base_url('admin/reseller-products/' . $editingProduct['id']) : base_url('admin/reseller-products') ?>" method="post"><?= csrf_field() ?><div class="row g-3">
<div class="col-md-8"><label class="form-label">Nama produk</label><input class="form-control" name="nama" value="<?= esc(old('nama', $editingProduct['nama'] ?? '')) ?>" required></div>
<div class="col-md-4"><label class="form-label">SKU</label><input class="form-control text-uppercase" name="sku" value="<?= esc(old('sku', $editingProduct['sku'] ?? '')) ?>" required></div>
<div class="col-md-6"><label class="form-label">Model</label><input class="form-control" name="model_name" value="<?= esc(old('model_name', $editingProduct['model_name'] ?? '')) ?>" placeholder="Contoh: Raglan setelan" required></div>
<div class="col-md-6"><label class="form-label">Bahan</label><input class="form-control" name="material" value="<?= esc(old('material', $editingProduct['material'] ?? '')) ?>" placeholder="Contoh: Dryfit Milano" required></div>
<div class="col-md-4"><label class="form-label">Harga dasar / pcs</label><input class="form-control" type="number" min="1" step="1000" name="base_price" value="<?= esc(old('base_price', $editingProduct['base_price'] ?? '')) ?>" required></div>
<div class="col-md-4"><label class="form-label">Minimal order</label><input class="form-control" type="number" min="1" name="min_order" value="<?= esc(old('min_order', $editingProduct['min_order'] ?? 12)) ?>" required></div>
<div class="col-md-4"><label class="form-label">Estimasi produksi (hari)</label><input class="form-control" type="number" min="1" name="lead_time_days" value="<?= esc(old('lead_time_days', $editingProduct['lead_time_days'] ?? 7)) ?>" required></div>
<div class="col-md-6"><label class="form-label">Warna tersedia</label><input class="form-control" name="available_colors" value="<?= esc(old('available_colors', $editingProduct['available_colors'] ?? '')) ?>" placeholder="Hitam, Navy, Merah" required><small class="text-muted">Pisahkan dengan koma.</small></div>
<div class="col-md-6"><label class="form-label">Ukuran tersedia</label><input class="form-control" name="available_sizes" value="<?= esc(old('available_sizes', $editingProduct['available_sizes'] ?? '')) ?>" placeholder="XS, S, M, L, XL, XXL" required><small class="text-muted">Pisahkan dengan koma.</small></div>
<div class="col-md-6"><label class="form-label">Gambar</label><select class="form-select" name="reseller_image"><option value="">Tanpa gambar</option><?php foreach ($imageOptions as $image): ?><option value="<?= esc($image, 'attr') ?>" <?= old('reseller_image', $editingProduct['reseller_image'] ?? '') === $image ? 'selected' : '' ?>><?= esc($image) ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1" <?= (string) old('status', $editingProduct['status'] ?? 1) === '1' ? 'selected' : '' ?>>Aktif</option><option value="0" <?= (string) old('status', $editingProduct['status'] ?? 1) === '0' ? 'selected' : '' ?>>Draft</option></select></div>
<div class="col-12"><label class="form-label">Deskripsi</label><textarea class="form-control" name="description" rows="3"><?= esc(old('description', $editingProduct['description'] ?? '')) ?></textarea></div>
</div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary"><i class="fas fa-save me-2"></i><?= $editing ? 'Simpan Perubahan' : 'Tambah Produk' ?></button><?php if ($editing): ?><a class="btn btn-light" href="<?= base_url('admin/reseller-products') ?>">Batal</a><?php endif; ?></div></form></div></div>

<div class="admin-card"><div class="card-header"><i class="fas fa-boxes-stacked me-2"></i>Daftar Produk</div><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Produk</th><th>Spesifikasi</th><th>Harga Dasar</th><th>MOQ/Produksi</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if ($products): foreach ($products as $product): ?><tr><td><strong><?= esc($product['nama']) ?></strong><br><small class="text-muted"><?= esc($product['sku']) ?></small></td><td><?= esc($product['model_name']) ?><br><small><?= esc($product['material']) ?></small></td><td><strong>Rp <?= number_format($product['base_price'], 0, ',', '.') ?></strong></td><td><?= (int) $product['min_order'] ?> pcs<br><small>± <?= (int) $product['lead_time_days'] ?> hari</small></td><td><span class="badge bg-<?= $product['status'] ? 'success' : 'secondary' ?>"><?= $product['status'] ? 'Aktif' : 'Draft' ?></span></td><td><div class="d-flex gap-2"><a href="<?= base_url('admin/reseller-products/edit/' . $product['id']) ?>" class="btn btn-sm btn-outline-primary"><i class="fas fa-pen"></i></a><form action="<?= base_url('admin/reseller-products/' . $product['id'] . '/delete') ?>" method="post" onsubmit="return confirm('Nonaktifkan produk ini?')"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form></div></td></tr><?php endforeach; else: ?><tr><td colspan="6" class="text-center py-5 text-muted">Belum ada produk reseller. Isi form di atas untuk mulai.</td></tr><?php endif; ?></tbody></table></div></div></div>
